hydra:
  run:
    dir: ${oc.env:MINESTUDIO_SAVE_DIR}/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra/job_logging: colorlog
hydra/hydra_logging: colorlog

model_path: '/nfs-shared/jarvisbase/pretrained/foundation-model-2x.model'
weights_path: '/nfs-shared/jarvisbase/pretrained/foundation-model-2x.weights'
project_id: 'tune_vpt_fd_2x'

dataset_dirs: 
  - '/nfs-shared-2/data/contractors/dataset_6xx'
  - '/nfs-shared-2/data/contractors/dataset_7xx'
  - '/nfs-shared-2/data/contractors/dataset_8xx'
  - '/nfs-shared-2/data/contractors/dataset_9xx'
  - '/nfs-shared-2/data/contractors/dataset_10xx'

batch_size: 8
num_workers: 8
prefetch_factor: 4
split_ratio: 0.9
devices: 8
logger: 'wandb'
learning_rate: 0.0000181
warmup_steps: 1000
weight_decay: 0.000181