hydra:
  run:
    dir: ${oc.env:MINESTUDIO_SAVE_DIR}/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra/job_logging: colorlog
hydra/hydra_logging: colorlog

data:
  mode: "raw"
  dataset_dirs:
    - "/nfs-shared-2/data/contractors-new/dataset_6xx"
    - "/nfs-shared-2/data/contractors-new/dataset_7xx"
    - "/nfs-shared-2/data/contractors-new/dataset_8xx"
    - "/nfs-shared-2/data/contractors-new/dataset_9xx"
    - "/nfs-shared-2/data/contractors-new/dataset_10xx"
  frame_width: 128
  frame_height: 128
  win_len: 128
  action_chunk_size: 32

policy:
  attention_heads: 8
  attention_mask_style: "clipped_causal"
  attention_memory_size: 256
  diff_mlp_embedding: False
  hidsize: 1024
  img_shape: [128, 128, 3]
  impala_chans: [16, 32, 32]
  impala_kwargs:
    post_pool_groups: 1
  impala_width: 4
  init_norm_kwargs:
    batch_norm: False
    group_norm_groups: 1
  n_recurrence_layers: 4
  only_img_input: True
  pointwise_ratio: 4
  pointwise_use_activation: False
  recurrence_is_residual: True
  recurrence_type: "transformer"
  timesteps: 10
  use_pointwise_layer: True
  use_pre_lstm_ln: False

action:
  dim_cond: 1024
  dim_input: 704
  depth: 3
  width: 512

mineclip:
  arch: "vit_base_p16_fz.v2.t2"
  hidden_dim: 512
  image_feature_dim: 512
  mlp_adapter_spec: "v0-2.t0"
  pool_type: "attn.d2.nh8.glusw"
  resolution: [160, 256]

batch_size: 8
num_workers: 4
precision: "bf16"
prefetch_factor: 4
split_ratio: 0.9
devices: 4
learning_rate: 0.00004
warmup_steps: 2000
weight_decay: 0.000181
save_freq: 2000
objective_weight: 0.01
shuffle_episodes: False
episode_continuous_batch: False
